### ISSUE TITLE
sqlsrv database error

### ISSUE THREAD

**Issue by robthornley** [ci-bonfire/Bonfire#1220]
When trying to install onto a Microsoft SQL Server database using the sqlsrv driver.
```
A Database Error Occurred

Error Number: 42000/2716

[Microsoft][SQL Server Native Client 11.0][SQL Server]Column, parameter, or variable #2: Cannot specify a column width on data type int.

IF NOT EXISTS (SELECT * FROM sysobjects WHERE ID = object_id(N'"bf_schema_version"') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) CREATE TABLE "bf_schema_version" ( "type" varchar(40) NOT NULL, "version" int(4) DEFAULT 0 NOT NULL, CONSTRAINT "pk_bf_schema_version" PRIMARY KEY("type") )

Filename: D:/wwwroot/ci/bonfire/modules/migrations/libraries/Migrations.php

Line Number: 727
```

**Comment by silverark** [comment]
This issue has been fixed in codeigniter: https://github.com/bcit-ci/CodeIgniter/issues/861

**Comment by robthornley** [comment]
how do i go about fixing this within bonfire?

**Comment by silverark** [comment]
You can update the whole of codeigniter, but it might have knock on effects with CIBonfire. 
It's not recommended, but you could either update the migration files removing the constraint on all integers or file the following file database/drivers/sqlsrv/sqlsrv_forge.php under bonfire and replace with the version here: https://github.com/bcit-ci/CodeIgniter/blob/af4d55da04b8d8750b59e04e46463d525237b74b/system/database/drivers/sqlsrv/sqlsrv_forge.php

**Comment by jayjfletcher** [comment]
I'm having the same issue at the moment trying to connect with mssql. I've swapped the drivers out for the latest and still get this error.

**Comment by silverark** [comment]
@jayjfletcher  Did you see the full commit above? There is also a mssql driver: mssql_forge.php. Were you using mssql or the sqlsrv driver? CAn you post your full error message?

**Comment by mwhitneysdsu** [comment]
There shouldn't be any issues with upgrading CI to 3.0.4 in Bonfire. I'm running it on my website right now, I just haven't gotten around to updating the project.

**Comment by jayjfletcher** [comment]
I did look at the comment above. I also updated CI. Unfortunately, the issue still persists. Looking at issue #bcit-ci/CodeIgniter#861. That fix was 3 years ago. It seems the driver has since changed completely, reintroducing the issue.

**Comment by mwhitneysdsu** [comment]
It looks like narf has this slated for 3.0.7, but hopefully you can use the changes he published if you need them before that release.
